### ISSUE TITLE
[Tracking] Kyverno kuttl enhancement task list

### ISSUE THREAD

**Issue by chipzoller** [kyverno/kuttl#18]
Kyverno's version of kuttl needs several enhancements to make it eminently usable for Kyverno's test needs. This issue captures all of the enhancements needed not present in upstream and which we intend to add here.

- [x] Wait for Namespace deletion (#6)
- [x] Support for individual test case disabling (#5)
- [x] Support for simple declaration of manifest application failure (#17)
- [x] Support for directory recursion (#16)
- [x] Show full path to test cases in output (#4)
- [x] #25
- [x] #24
- [x] #26
- [x] #22
- [x] #23

**Comment by chipzoller** [comment]
We've reached a point of scale where we really could use the failure aggregation feature, @eddycharly. It's becoming difficult to find the failures in a list of about 150 test cases.

**Comment by arup1221** [comment]
I am interested on it , could you please prefer some resources to understand the project and outcomes.

**Comment by chipzoller** [comment]
See the README in this project and the parent of the fork for more details on what it is. Please make your application if interested.

**Comment by arup1221** [comment]
Yes, I am interested and I definitely apply for it.

**Comment by arup1221** [comment]
Yes, I am interested on it.

**Comment by AdiAkhileshSingh15** [comment]
I'm really interested in this project and I plan to apply as a Mentee once LFX Fall applications are open. 
Also, I'm curious to know if there are any beginner-friendly issues available for me to start contributing and get to know more about kyverno and the project.

Thanks a lot! Any help would be highly appreciated.

**Comment by chipzoller** [comment]
Are you asking about beginner-friendly issues for kuttl or just anywhere in the Kyverno organization? If the latter, we assign labels `good first issue` to these so you can find them.

**Comment by AdiAkhileshSingh15** [comment]
No, i was asking about beginner-friendly issues for kuttl. Related to this tasklist, so that i can get to understand it better.

**Comment by chipzoller** [comment]
What we have here is currently what is triaged. #25 is going to be the easiest.

**Comment by AdiAkhileshSingh15** [comment]
Ohkay! I'll go through that. Any resources that you would suggest me, to understand kuttl better?

**Comment by chipzoller** [comment]
The [docs](https://kuttl.dev/), this repo, and the huge number of tests in [kyverno/policies](https://github.com/kyverno/policies) and [kyverno/kyverno](https://github.com/kyverno/kyverno/tree/main/test/conformance/kuttl).

**Comment by AdiAkhileshSingh15** [comment]
Thanks a lot!

**Comment by chipzoller** [comment]
All the LFX mentorships are application based. You must apply and then be selected to work on issues designated mentorship issues. Application does not guarantee selection.

**Comment by PurviChaurasia** [comment]
Hi @chipzoller just wanted to express my interest in this project. Looking at past mentees as Kyverno, most of them mentioned that selection is based on application and resume. I wanted to know what are other factors that you consider while looking for mentees?

**Comment by chipzoller** [comment]
We consider your experience by what work you've done as apparent on GitHub and other performance or experience-related factors.

**Comment by PurviChaurasia** [comment]
Thanks a lot!

**Comment by h4shk4t** [comment]
Hi, my name is Ashutosh Srivastava, I am very interested in applying for this project for LFX this fall. I have good experience with working with Kubernetes via Golang API. I have even worked on cloud security and pod security and would love to contribute to kyverno.

Best Regards
Ashutosh Srivastava
